### PR TITLE
Enhancement: Allow installation with phpstan/phpstan:~0.12.2

### LINKED ISSUE #69: phpstan-prophecy with PHPStan 0.12.0
Hello,

PHPStan 0.12.0 came out recently and it looks like `phpstan-prophecy` is not compatible with it at the moment. Even if I try to get around the version restriction, when running PHPStan I get the following error:

_Fatal error: Class JanGregor\Prophecy\Reflection\ObjectProphecyMethodReflection contains 7 abstract methods and must therefore be declared abstract or implement the remaining methods (PHPStan\Reflection\MethodReflection::isDeprecated, PHPStan\Reflection\MethodReflection::getDeprecatedDescription, PHPStan\Reflection\MethodReflection::isFinal, ...) in /var/www/html/vendor/jangregor/phpstan-prophecy/src/Reflection/ObjectProphecyMethodReflection.php on line 12_

I saw https://github.com/Jan0707/phpstan-prophecy/pull/67, however is there any timeline as to when this can be addressed?

Thanks!

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] allows installation with `phpstan/phpstan:~0.12.2`

Fixes #69.

💁‍♂ For reference, see https://github.com/phpstan/phpstan/releases/tag/0.12.2.

### CODE REVIEW

**Comment by hugochinchilla** [comment]
I need this to upgrade my project to symfony 5

**Comment by gnutix** [comment]
@Jan0707 with the new PHPStan release bringing amazing features, I guess it would be a good idea to merge this ASAP if it just works!

**Comment by AlexandruGG** [comment]
Simply lifting the version restriction is not sufficient, as this error pops up when running PHPStan:

```Fatal error: Class JanGregor\Prophecy\Reflection\ObjectProphecyMethodReflection contains 7 abstract methods and must therefore be declared abstract or implement the remaining methods (PHPStan\Reflection\MethodReflection::isDeprecated, PHPStan\Reflection\MethodReflection::getDeprecatedDescription, PHPStan\Reflection\MethodReflection::isFinal, ...) in /var/www/html/vendor/jangregor/phpstan-prophecy/src/Reflection/ObjectProphecyMethodReflection.php on line 12```

**Comment by localheinz** [comment]
@AlexandruGG 

Ha, thank you - going to take a look later!

**Comment by PedroTroller** [comment]
@localheinz I made your PR compatible with the new structure of phpstan.
https://github.com/localheinz/phpstan-prophecy/pull/1

**Comment by localheinz** [comment]
Thank you, @PedroTroller!

**Comment by localheinz** [comment]
@Jan0707 

Any chance of getting this merged soon?

I think everyone in the PHP community using `phpstan/phpstan` is eagerly awaiting a new release, so that we can update to `phpstan/phpstan:~0.12.2` and benefit from the new features.

🤓

**Comment by Jean85** [comment]
> I need this to upgrade my project to symfony 5

@hugochinchilla no you don't: PHPStan 0.12 works through a shim with a PHAR to avoid dependency collisions; if PHPStan 0.11 is blocking you, you can use PHPStan shim 0.11; it's a different package, but you get the same benefit without forcing the upgrade right now.

**Comment by gnutix** [comment]
@Jean85 It can be more complicated than that [unfortunately](https://github.com/phpstan/phpstan/issues/2555)...

**Comment by Jean85** [comment]
BTW the CI is green on this PR: https://travis-ci.org/Jan0707/phpstan-prophecy/builds/622588044

The integration is broken, @Jan0707 needs to fix it.

**Comment by gnutix** [comment]
Any chance @Jan0707 might react in the upcoming days (as there's no answer from him for a week already) ? Or should someone provide a fork in the meantime ?

**Comment by Jean85** [comment]
This PR is usable as a fork already, you just have to declare in your composer.json to use https://github.com/localheinz/phpstan-prophecy/ as a repo, and 758261b as a commit

**Comment by localheinz** [comment]
Quick heads-up: I reached out by ✉️, let's see what is going to happen!

🤓

**Comment by AlexandruGG** [comment]
> This PR is usable as a fork already, you just have to declare in your composer.json to use https://github.com/localheinz/phpstan-prophecy/ as a repo, and [758261b](https://github.com/Jan0707/phpstan-prophecy/commit/758261b0bb2266b27a8c84fb7552580fa1ba211e) as a commit

Easier to add Prophecy related errors to ignoreErrors 😄, like :  

``` '#Call to an undefined method Prophecy\\Prophecy\\ObjectProphecy::[a-zA-Z0-9_]+\(\).#'```

**Comment by localheinz** [comment]
@AlexandruGG 

>Easier to add Prophecy related errors to ignoreErrors 😄, like :
>
> `'#Call to an undefined method Prophecy\\Prophecy\\ObjectProphecy::[a-zA-Z0-9_]+\(\).#'`

This is probably the best solution until this gets released.

**Comment by localheinz** [comment]
Thank you, @AlexandruGG, @core23,  @gnutix, @hugochinchilla, @Jean85, and @PedroTroller!

**Pull request merged**
