### PR TITLE
allow also to use phpunit 7.0

### PR DESCRIPTION
**Pull request by Engerim**
After PHPUnit 7.0 is released, this change allows to use phpstan-prophecy in combination with phpunit ^7.0

### CODE REVIEW

**Comment by Jean85** [comment]
Do we know of any breaking change in PHPUnit 7 that could break this extension?

**Comment by Jan0707** [comment]
Will try later tonight or tomorrow - I am a bit handicapped today because of super-bowl-induced-fatigue ;)

**Comment by lku** [comment]
I've just tested this branch on seven pretty large projects, and everything seems ok. Prophecy version constraint did not changed in PHPUnit v7, so I think there is nothing to break (ahem).

**Comment by Jan0707** [comment]
Merged and tagged new version. Thanks everyone !

**Pull request merged**
