### PR TITLE
Enhancement: Add PHP 7.3 to Travis CI build matrix

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] adds PHP 7.3 to the Travis CI build matrix

### CODE REVIEW

**Comment by localheinz** [comment]
@Jan0707 

We have noticed that it appears as if builds on Travis CI are not triggered. They are, however, only the build status does not appear. Not sure what is wrong. See https://travis-ci.org/Jan0707/phpstan-prophecy/builds/479337767.

/cc @Jean85

**Comment by Jean85** [comment]
This failure highlights with `WITH_LOCKED` doesn't seem a good practice to me. It doesn't work well, we should use the highest vendors when not testing with `--prefer-lowest`.

https://travis-ci.org/Jan0707/phpstan-prophecy/jobs/479337775

**Comment by localheinz** [comment]
@Jean85 

> This failure highlights with WITH_LOCKED doesn't seem a good practice to me. It doesn't work well, we should use the highest vendors when not testing with `--prefer-lowest`.

No, the failure highlights that the currently locked version of `friendsofphp/php-cs-fixer` doesn't work on PHP 7.3, that's why I suggest to update it in #34.

Note that we are *installing* dependencies in the `style` stage.

If we *updated* dependencies in the `style` stage, we could potentially pull in newer versions of `friendsofphp/php-cs-fixer`, which in turn could could potentially fix the existing code with a different outcome than the locked version of `friendsofphp/php-cs-fixer`.

**Comment by Jean85** [comment]
That would be a bad SemVer handling by that package, and it could be limited by restraining more that constraint. I still advocate updating deps instead of installing.

**Comment by localheinz** [comment]
Build failure is unrelated and fixed with #40.

**Comment by localheinz** [comment]
Build failure is unrelated and fixed with #45.

**Comment by localheinz** [comment]
Blocked by #34.

**Comment by Jan0707** [comment]
#34 is merged. Please update :)

**Comment by localheinz** [comment]
Thank you, @Jan0707!

**Pull request merged**
