### PR TITLE
Increase CI matrix to test against more recent PHPUnit & PHP versions

### PR DESCRIPTION
**Pull request by Jean85**
This is a followup to #348, and tries to add more configuration to test.
Let me know if you want me to follow some specific approach, for now I'm trying a balance between testing all the versions and not having too many jobs to execute.

@Jan0707 WDYT about dropping the custom actions for Composer and migrati to [`ramsey/composer-install`](https://github.com/ramsey/composer-install)? It has all in one, caching included.

### CODE REVIEW

**Comment by Jean85** [comment]
SA failure is due to the fact that we're using `nikic/php-parser` v4, while PHPStan 2 uses v5 internally.

```
$ composer why-not nikic/php-parser 5
phpunit/php-code-coverage 9.0.0 requires nikic/php-parser (^4.7) 
sebastian/complexity      2.0.0 requires nikic/php-parser (^4.7) 
sebastian/lines-of-code   1.0.0 requires nikic/php-parser (^4.6) 
```
The same failure does not happen in the CI job with PHPUnit 9.6.0, since it allows v5 since [`php-code-coverage` v9.2.30](https://packagist.org/packages/phpunit/php-code-coverage#9.2.30)

I fixed it by running `composer update phpunit/php-code-coverage nikic/php-parser -w --minimal-changes`, the new `--minimal-changes` option is great! :smile:

**Review by alexander-schranz — APPROVED** [review]

**Comment by Jean85** [comment]
> @Jan0707 WDYT about dropping the custom actions for Composer and migrati to [`ramsey/](https://github.com/ramsey/composer-install)? It has all in one, caching included.

@Jan0707 I did this in the last commit, let me know if it's ok or if I should drop it.

**Comment by Jean85** [comment]
Sorry, I needed to ping you @alexander-schranz :sweat:

**Comment by alexander-schranz** [comment]
Fine with the using ramsey github action.

**Pull request merged**
