### PR TITLE
Enhancement: Use dependabot

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] adds a [Dependabot](https://dependabot.com) - and removes the [Violinist](https://violinist.io) - configuration

💁‍♂ This probably requires to set up Dependabot and disable Violinist - is this something you would be up for, @Jan0707?

### CODE REVIEW

**Comment by Jan0707** [comment]
What's the benefit that we see here ?

**Comment by localheinz** [comment]
@Jan0707 

Dependabot can be configured to

- update `composer.json` as well
- automatically merge pull requests when the build passes

For reference, see https://dependabot.com/docs/config-file/.

I believe the most compelling argument is that pull requests can be automatically merged.

Apart from that, Dependabot has been acquired by GitHub and is the de-facto standard solution for updating dependencies for a wide range of package managers.

**Comment by localheinz** [comment]
@Jan0707 

Violinist currently updates `composer.lock` only, which is pretty much useless, as we run builds against lowest, locked, and highest versions.

**Comment by Jan0707** [comment]
I feel this would bind us even more to Github and its eco system. Is that a shared concern? If not then we could go ahead.

**Comment by Jan0707** [comment]
ping @localheinz 
I assume you think this is a worthwhile trade-off ?

**Comment by localheinz** [comment]
@Jan0707 

With [Dependabot moving natively into GitHub](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/), I think that the switch makes a lot of sense.

**Pull request merged**
