### PR TITLE
Enhancement: Enforce PSR-2 with friendsofphp/php-cs-fixer

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] requires `friendsofphp/php-cs-fixer`
* [x] adds a basic configuration for `friendsofphp/php-cs-fixer`
* [x] runs `php-cs-fixer` in `dry-run` mode on Travis
* [x] runs `php-cs-fixer` to fix coding style issues

### CODE REVIEW

**Comment by localheinz** [comment]
@Jan0707 

Looks like **Auto Cancellation** is activated, what do you think about disabling it?

Below a screenshot when disabled:

screen shot 2018-10-29 at 19 33 58

See https://travis-ci.org/Jan0707/phpstan-prophecy/settings.

**Comment by Jan0707** [comment]
Blocked issue #28 has been resolved. Once this has been updated, we can merge this.

**Comment by localheinz** [comment]
@Jan0707 

Appears as if the commit statuses are not updated correctly. Builds are running, though, see https://travis-ci.org/Jan0707/phpstan-prophecy/pull_requests.

**Comment by localheinz** [comment]
Thank you, @Jan0707 and @Jean85!

**Pull request merged**
