### PR TITLE
Enhancement: Update friendsofphp/php-cs-fixer

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] updates `friendsofphp/php-cs-fixer`

💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/compare/v2.13.1...v2.15.0.

### CODE REVIEW

**Comment by localheinz** [comment]
@Jean85 

The currently used version of `friendsofphp/php-cs-fixer` does not work on PHP 7.3.

Feel free to open a PR to make the changes you like!

**Comment by Jean85** [comment]
No change is needed. The current constraint allows 2.14, the issue is in the fact that we're using the .lock, as I suggested in https://github.com/Jan0707/phpstan-prophecy/pull/32#issuecomment-453967691

I can agree that we can have ONE single CI job that uses the .lock, but all the others shouldn't use it, for this exact reason (and many others).

**Comment by localheinz** [comment]
Build failure is unrelated and fixed with #40.

**Comment by localheinz** [comment]
Build failure is unrelated and fixed with #45.

**Comment by localheinz** [comment]
Thank you, @Jan0707!

**Pull request merged**
